### ISSUE TITLE
Reconsidering the state history

### ISSUE THREAD

**Issue by tmedwards** [tmedwards/sugarcube-3#20]
Does the state history really need to exist?

## Reasoning

The state history is a holdover from the original two story formats, *Jonah* and *Sugarcane*.  There it existed to allow players to back up and revisit previous decisions and/or scenes as those formats did not have the ability to truly save the playthrough state—the path taken was reflected within the URL fragment identifier, but that failed to record anything else.

All versions of SugarCube, by default, have the ability to save playthrough state, so a separate system to allow players to revisit previous decisions and/or scenes is not really necessary.

## Pros & Cons

With only a single, active, state:

### Pros

* There would be no need for moment to moment cloning, which would alleviate many pain points for developers—e.g., broken references for one, though serialization would still need to be modified to handle that.
* There would be no need for delta coding the serialized state.
* The serialized state, as seen in sessions and saves, would become smaller—much smaller for anyone not having set `Config.history.maxStates` to `1`.
* [Maybe?] The saved state *could possibly* become the active state, so sessions and saves would reflect the current game state at the moment the save was made.  Thus, interactive sections would become persistent.
* Several of the other items on this list would help speed up games that currently experience slowdowns—both while playing and saving/loading.

### Cons

* If the player didn't make a save, they can't simply revisit a previous moment.  That's fairly common in other games, however, and some developers set their games up that way anyway, so that's not a huge issue.
* [Maybe?] If the saved state were made the active state, sessions and saves would reflect the current game state at the moment the save was made.  This is different from what developers are used to, so it has the potential to be a tripping hazard—e.g., a scene written with assumptions about variable state could find those assumptions invalidated.

**Comment by Uzume** [comment]
How about a compromise? I suggest instead scv3 remove all the in-memory moment snapshots affiliated with the current history mechanisms and instead leveraging and extending the playthrough session mechanisms with a long bunch of autosave moment snapshots and adding a history list across the moment snapshots. This basically keeps the history but pushes it all out of memory into session data. Then scv3 can still traverse the history but would have to do it slower loading historical moment state from session data. I think it would make sense to have normal saves contain the complete history by pulling in the session data and building the save data and then doing the reverse and rebuilding the session data from saved data during a load.

This compromise would remove virtually all history data from in-memory use (it might make sense to keep the history list cached in memory so it can know which session snapshot to pull during a history jump) except when either saving and loading or when jumping around in history. Both of those are used much less frequently and if they had performance impacts it might not be as problematic.

I believe that means the history would still work, save data would remain the same size and most history data would migrate from being kept in-memory to session data and the end result would be a more responsive game engine except for the larger impacts to load and saves and history jumps.

Maybe I am misunderstanding something, however, this was my idea based on my limited understanding. Please feel free to educate me.

**Comment by tmedwards** [comment]
The state history has been pruned.  The ability to have multiple auto saves have been added to compensate.

**Comment by Uzume** [comment]
> 
> 
> The state history has been pruned. The ability to have multiple auto saves have been added to compensate.

@tmedwards Does this mean you have just decided or is there code demonstrating this? If there is code, where does one find it. I understand it is likely alpha at best.

**Comment by tmedwards** [comment]
It was done as part of a large messy commit, which is why I didn't bother with a reference—that and I forgot.  The commit in question: bb09207.

Though, you're probably better off looking at the files in question if you just wish to check out the code:

1. **`State`:** https://github.com/tmedwards/sugarcube-3/blob/pre-alpha/src/state.js
2. **`Save`:** https://github.com/tmedwards/sugarcube-3/blob/pre-alpha/src/save.js

There are knock-on changes that followed in other files—e.g., the reworking of the visit family of user functions.

In case you're unaware of it, my *"keep myself abreast of what's going on"* changelog can be found at: https://github.com/tmedwards/sugarcube-3/blob/pre-alpha/CHANGELOG.md

**Comment by Uzume** [comment]
@tmedwards Thanks, I should have known to look at the "bad man" commit.
