### ISSUE TITLE
Custom spinner

### ISSUE THREAD

**Issue by MarcoByte** [tmedwards/sugarcube-3#29]
Dear TME,

I will keep it short,

Some people, like me and a user named Bogdan, would love to make a custom spinner.

Going through the trouble of:
`html[data-init=loading] #init-loading {
    animation: none;
    background: url("icons/load.gif") no-repeat center center;
    background-size: contain;
    border: none;
    height: 10em;
    width: 10em;
}`

Inside `modules/spinner.css` and then calling it with `call tweego -o export/index.html --module=modules src` is a lot of trouble, and requires both tweego and undocumented things (I couldn't find it on the github/motoslave), thanks to lovely Cyrus and your older posts in the discord we were able to build it! But I would love to be able to either change it from the story css or maybe even a macro.

This is my first "issue" ever, sorry if it didn't fit the format!

Yours sincerely,
Bogdan and Sjoerd

**Comment by tmedwards** [comment]
The `init-screen.css` is listed under [Built-in Stylesheets](http://www.motoslave.net/sugarcube/2/docs/#css-built-ins).

As far as allowing the loading spinner to be replaced, the process you've undertaken is the recommended method to replace it.

The issue with attempting to replace it from within SugarCube is that SugarCube doesn't run until the page has already finished loading.  This somewhat defeats the point of replacing the loading spinner as players will see the default spinner until SugarCube has loaded and run your code finally replacing it.

This is simply a chicken and egg kind of problem.  It's best resolved before the spinner itself loads, which you've done.

**Comment by MarcoByte** [comment]
Alright, I see what you mean, thanks for the fast reply, is there a way this can be added to the documentation (how to change it)? Otherwise, I will try to spread the knowledge on Reddit/discord/anywhere :D

p.s.
If there is an example on motoslave I accidentally skipped it, sorry!
